# add your desired knowledge graph components here

immune receptor sequence:
  is_a: polypeptide

t cell receptor sequence:
  is_a: immune receptor sequence
  properties:
      junction_aa: str
      v_call : str
      j_call : str
      CDR1 : str
      CDR2 : str
      species : str
  
b cell receptor sequence:
  is_a: immune receptor sequence

tra sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: tra

trb sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: trb

igh sequence:
  is_a: b cell receptor sequence
  represented_as: node
  input_label: igh

igl sequence:
  is_a: b cell receptor sequence
  represented_as: node
  input_label: igl

epitope:
  is_a: polypeptide
  represented_as: node
  input_label: epitope
  properties:
    protein: str
    IEDB_ID: str
    antigen_name: str
    antigen_organism: str
    MHC_class: str
    MHC_gene_1: str
    MHC_gene_2: str


t cell receptor sequence to epitope association:
  is_a: association
  represented_as: edge
  input_label: [tra_to_epitope, trb_to_epitope]

b cell receptor sequence to epitope association:
  is_a: association
  represented_as: edge
  input_label: [igh_to_epitope, igl_to_epitope]

alpha sequence to beta sequence association:
  is_a: association
  represented_as: edge
  input_label: tra_to_trb

heavy sequence to light sequence association:
  is_a: association
  represented_as: edge
  input_label: igh_to_igl
