# add your desired knowledge graph components here

t cell receptor sequence:
  is_a: nucleic acid sequence motif

tra sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: TRA

trb sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: TRB

epitope:
  is_a: protein sequence motif
  represented_as: node
  input_label: Epitope

t cell receptor sequence to epitope association:
  is_a: association
  represented_as: edge
  input_label: TCR_Sequence_To_Epitope