# add your desired knowledge graph components here

immune receptor sequence:
  is_a: polypeptide

t cell receptor sequence:
  is_a: immune receptor sequence  
  
b cell receptor sequence:
  is_a: immune receptor sequence  

b cell receptor sequence:
  is_a: polypeptide

tra sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: TRA

trb sequence:
  is_a: t cell receptor sequence
  represented_as: node
  input_label: TRB

igh sequence:
  is_a: b cell receptor sequence
  represented_as: node
  input_label: IGH

igl sequence:
  is_a: b cell receptor sequence
  represented_as: node
  input_label: IGL

epitope:
  is_a: polypeptide  # TODO probably not semantically correct
  represented_as: node
  input_label: Epitope

t cell receptor sequence to epitope association:
  is_a: association
  represented_as: edge
  input_label: TCR_Sequence_To_Epitope

b cell receptor sequence to epitope association:
  is_a: association
  represented_as: edge
  input_label: BCR_Sequence_To_Epitope

alpha sequence to beta sequence association:
  is_a: association
  represented_as: edge
  input_label: TRA_To_TRB

heavy sequence to light sequence association:
  is_a: association
  represented_as: edge
  input_label: IGH_To_IGL
