row:
  chain_id:
    columns: [chain_2_type, chain_2_cdr3, chain_2_v_call]
    to_subject: chain_2

transformers:
  - map:
      column: chain_2_type
      to_property: locus
      for_object: chain_2
  - map:
      column: chain_2_cdr3
      to_property: cdr3_aa
      for_object: chain_2
  - map:
      column: chain_2_junction_aa
      to_property: junction_aa
      for_object: chain_2
  - map:
      column: chain_2_v_call
      to_property: v_call
      for_object: chain_2
  - map:
      column: chain_2_j_call
      to_property: j_call
      for_object: chain_2
  - map:
      column: chain_2_organism
      to_property: organism
      for_object: chain_2
  - map:
      column: chain_2_complete
      to_property: complete
      for_object: chain_2

  - prefixed_id:
      columns: [chain_2_v_call]
      prefix: v_gene
      to_object: v_gene
      via_relation: chain_2_to_v_gene

  - prefixed_id:
      columns: [chain_2_j_call]
      prefix: j_gene
      to_object: j_gene
      via_relation: chain_2_to_j_gene
