row:
  chain_id:
    columns: [chain_2_type, chain_2_cdr3, chain_2_v_call]
    match_type_from_column: chain_2_type
    match:
      - TRB:
          to_subject: trb
      - IGL:
          to_subject: igl

transformers:
  - map:
      column: chain_2_type
      to_property: type
      for_objects: [trb, igl]
  - map:
      column: chain_2_cdr3
      to_property: cdr3
      for_objects: [trb, igl]
  - map:
      column: chain_2_v_call
      to_property: v_call
      for_objects: [trb, igl]
  - map:
      column: chain_2_j_call
      to_property: j_call
      for_objects: [trb, igl]
  - map:
      column: chain_2_organism
      to_property: organism
      for_objects: [trb, igl]

  - cat_format:
      columns: [iedb_iri]
      format_string: "epitope:{iedb_iri}"
      match_type_from_column: chain_2_type
      match:
        - TRB:
            to_object: epitope
            via_relation: trb_to_epitope
        - IGL:
            to_object: epitope
            via_relation: igl_to_epitope

  - map:
      column: epitope_sequence
      to_property: epitope_sequence
      for_object: epitope
  - map:
      column: iedb_iri
      to_property: iedb_iri
      for_object: epitope
  - map:
      column: antigen_name
      to_property: antigen_name
      for_object: epitope
  - map:
      column: antigen_species
      to_property: antigen_species
      for_object: epitope
  - map:
      column: MHC_class
      to_property: MHC_class
      for_object: epitope
  - map:
      column: MHC_gene_1
      to_property: MHC_gene_1
      for_object: epitope
  - map:
      column: MHC_gene_2
      to_property: MHC_gene_2
      for_object: epitope
  - map:
      column: PMID
      to_property: PMID
      for_object: epitope
  - map:
      column: tissue
      to_property: tissue
      for_object: epitope
